; Script generated by Antigravity AI for EFPL Desktop IDE

[Setup]
AppId={{EFPL-IDE-2026}}
AppName=EFPL Desktop IDE
AppVersion=1.3
AppPublisher=EFPL
DefaultDirName={autopf}\EFPL IDE
DefaultGroupName=EFPL IDE
AllowNoIcons=yes
OutputDir=C:\Users\shanmuga mani\OneDrive\Documents\EFPL_VERSION_1\installer_output
OutputBaseFilename=EFPL_IDE_Setup
SetupIconFile=C:\Users\shanmuga mani\OneDrive\Documents\EFPL_VERSION_1\assets\app_icon.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\shanmuga mani\OneDrive\Documents\EFPL_VERSION_1\dist\main\main.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\shanmuga mani\OneDrive\Documents\EFPL_VERSION_1\dist\main\_internal\*"; DestDir: "{app}\_internal"; Flags: ignoreversion recursesubdirs createallsubdirs
; Include assets and workspace if they are not already in _internal
Source: "C:\Users\shanmuga mani\OneDrive\Documents\EFPL_VERSION_1\assets\*"; DestDir: "{app}\assets"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\shanmuga mani\OneDrive\Documents\EFPL_VERSION_1\workspace\*"; DestDir: "{app}\workspace"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\EFPL IDE"; Filename: "{app}\main.exe"
Name: "{autodesktop}\EFPL IDE"; Filename: "{app}\main.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\main.exe"; Description: "{cm:LaunchProgram,EFPL IDE}"; Flags: nowait postinstall skipifsilent
